### ISSUE TITLE
getting all the surface names from pyfluent

### ISSUE THREAD

**Issue by g-pagliuca** [ansys/pyfluent-visualization#371]
### 📝 Description of the feature

Hi there, it would be nice to be able to gather the surface names directly from pyfluent. 
At the moment you need to know that upfront or open the GUI.

### 💡 Steps for implementing the feature

No clue :-)

**Comment by prmukherj** [comment]
@g-pagliuca, try using "surfaces_list.allowed_values". I think this is what you want. Please let us know if anything else is needed.

**Comment by g-pagliuca** [comment]
Indeed, exactly what i needed, thanks ;-)

**Comment by cons013** [comment]
@prmukherj how exactly do you use this function? I can only find a single example in the documentation:

mesh = Mesh(solver, new_instance_name="mesh")
mesh.surfaces_list = mesh.surfaces_list.allowed_values()

But this doesn't work since 'Mesh' is undefined and there is no mesh module that I can import.

Cheers

**Comment by prmukherj** [comment]
> [@prmukherj](https://github.com/prmukherj) how exactly do you use this function? I can only find a single example in the documentation:
> 
> mesh = Mesh(solver, new_instance_name="mesh") mesh.surfaces_list = mesh.surfaces_list.allowed_values()
> 
> But this doesn't work since 'Mesh' is undefined and there is no mesh module that I can import.
> 
> Cheers

You can find an overall end-to-end working example in the documentation which you can follow.
https://visualization.fluent.docs.pyansys.com/version/stable/examples/00-postprocessing/post_processing_exhaust_manifold.html#sphx-glr-examples-00-postprocessing-post-processing-exhaust-manifold-py
Thank you.

**Comment by cons013** [comment]
> > [@prmukherj](https://github.com/prmukherj) how exactly do you use this function? I can only find a single example in the documentation:
> > mesh = Mesh(solver, new_instance_name="mesh") mesh.surfaces_list = mesh.surfaces_list.allowed_values()
> > But this doesn't work since 'Mesh' is undefined and there is no mesh module that I can import.
> > Cheers
> 
> You can find an overall end-to-end working example in the documentation which you can follow. https://visualization.fluent.docs.pyansys.com/version/stable/examples/00-postprocessing/post_processing_exhaust_manifold.html#sphx-glr-examples-00-postprocessing-post-processing-exhaust-manifold-py Thank you.

Hello,

Thanks for the reply, but this example shows the user inputting a list of surfaces they wish to display when visualising the mesh. I want to instead find a list of zones within the model, equivalent to the (inquire-zone-names) command. If I call:
`mesh1.surfaces_list.allowed_values()`
Then I get the error:
`coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
TypeError: 'list' object is not callable`

Is there a away to do this?

Best,
cons013

**Comment by prmukherj** [comment]
> > > [@prmukherj](https://github.com/prmukherj) how exactly do you use this function? I can only find a single example in the documentation:
> > > mesh = Mesh(solver, new_instance_name="mesh") mesh.surfaces_list = mesh.surfaces_list.allowed_values()
> > > But this doesn't work since 'Mesh' is undefined and there is no mesh module that I can import.
> > > Cheers
> > 
> > 
> > You can find an overall end-to-end working example in the documentation which you can follow. https://visualization.fluent.docs.pyansys.com/version/stable/examples/00-postprocessing/post_processing_exhaust_manifold.html#sphx-glr-examples-00-postprocessing-post-processing-exhaust-manifold-py Thank you.
> 
> Hello,
> 
> Thanks for the reply, but this example shows the user inputting a list of surfaces they wish to display when visualising the mesh. I want to instead find a list of zones within the model, equivalent to the (inquire-zone-names) command. If I call: `mesh1.surfaces_list.allowed_values()` Then I get the error: `coro = func() ^^^^^^ File "<input>", line 1, in <module> TypeError: 'list' object is not callable`
> 
> Is there a away to do this?
> 
> Best, cons013

Please use "mesh1.surfaces_list.allowed_values" instead of "mesh1.surfaces_list.allowed_values()" as allowed values call already returns a list which is not callable.

Please refer to the comment: https://github.com/ansys/pyfluent-visualization/issues/371#issuecomment-1985146903

Thank you.

**Comment by cons013** [comment]
> > > > [@prmukherj](https://github.com/prmukherj) how exactly do you use this function? I can only find a single example in the documentation:
> > > > mesh = Mesh(solver, new_instance_name="mesh") mesh.surfaces_list = mesh.surfaces_list.allowed_values()
> > > > But this doesn't work since 'Mesh' is undefined and there is no mesh module that I can import.
> > > > Cheers
> > > 
> > > 
> > > You can find an overall end-to-end working example in the documentation which you can follow. https://visualization.fluent.docs.pyansys.com/version/stable/examples/00-postprocessing/post_processing_exhaust_manifold.html#sphx-glr-examples-00-postprocessing-post-processing-exhaust-manifold-py Thank you.
> > 
> > 
> > Hello,
> > Thanks for the reply, but this example shows the user inputting a list of surfaces they wish to display when visualising the mesh. I want to instead find a list of zones within the model, equivalent to the (inquire-zone-names) command. If I call: `mesh1.surfaces_list.allowed_values()` Then I get the error: `coro = func() ^^^^^^ File "<input>", line 1, in <module> TypeError: 'list' object is not callable`
> > Is there a away to do this?
> > Best, cons013
> 
> Please use "mesh1.surfaces_list.allowed_values" instead of "mesh1.surfaces_list.allowed_values()" as allowed values call already returns a list which is not callable.
> 
> Please refer to the comment: [#371 (comment)](https://github.com/ansys/pyfluent-visualization/issues/371#issuecomment-1985146903)
> 
> Thank you.

Thanks, that seems to work, however this does not show every zone, only the mesh surfaces. Is there an equivalent command to (inquire-zone-names)?

**Comment by prmukherj** [comment]
> > > > > [@prmukherj](https://github.com/prmukherj) how exactly do you use this function? I can only find a single example in the documentation:
> > > > > mesh = Mesh(solver, new_instance_name="mesh") mesh.surfaces_list = mesh.surfaces_list.allowed_values()
> > > > > But this doesn't work since 'Mesh' is undefined and there is no mesh module that I can import.
> > > > > Cheers
> > > > 
> > > > 
> > > > You can find an overall end-to-end working example in the documentation which you can follow. https://visualization.fluent.docs.pyansys.com/version/stable/examples/00-postprocessing/post_processing_exhaust_manifold.html#sphx-glr-examples-00-postprocessing-post-processing-exhaust-manifold-py Thank you.
> > > 
> > > 
> > > Hello,
> > > Thanks for the reply, but this example shows the user inputting a list of surfaces they wish to display when visualising the mesh. I want to instead find a list of zones within the model, equivalent to the (inquire-zone-names) command. If I call: `mesh1.surfaces_list.allowed_values()` Then I get the error: `coro = func() ^^^^^^ File "<input>", line 1, in <module> TypeError: 'list' object is not callable`
> > > Is there a away to do this?
> > > Best, cons013
> > 
> > 
> > Please use "mesh1.surfaces_list.allowed_values" instead of "mesh1.surfaces_list.allowed_values()" as allowed values call already returns a list which is not callable.
> > Please refer to the comment: [#371 (comment)](https://github.com/ansys/pyfluent-visualization/issues/371#issuecomment-1985146903)
> > Thank you.
> 
> Thanks, that seems to work, however this does not show every zone, only the mesh surfaces. Is there an equivalent command to (inquire-zone-names)?
> 
> Edit: A somewhat functional workaround is using `solver.settings.setup.boundary_conditions.get_state()` and then something like ` for key, value in zone_dict.items():` but I don't know how reliable/portable this is.

Yes, these are settings-api command to inquire zone names. You can use this. But, visualization currently only supports getting mesh surfaces which can be redered.
Thank you.

**Comment by cons013** [comment]
I have found a workaround that actually seems good, but from [#1644](https://github.com/ansys/pyfluent/discussions/1644) I guess this will stop working at some point.

zones = [str(s) for s in solver.scheme_eval.scheme_eval("(inquire-zone-names)")]

**Comment by prmukherj** [comment]
> I have found a workaround that actually seems good, but from [#1644](https://github.com/ansys/pyfluent/discussions/1644) I guess this will stop working at some point.
> 
> zones = [str(s) for s in solver.scheme_eval.scheme_eval("(inquire-zone-names)")]

Yes, that's true. Please use the boundary_conditions from settings, instead.
