### ISSUE TITLE
Saving the dynamic html from command line

### ISSUE THREAD

**Issue by amscosta** [ansys/pyfluent-visualization#393]
Hi All,
Does anybody know how to convert the mouse operation of saving the dynamic html visualisation in
a text command line? Please see the attached image.
Any piece of advice is very welcome.
Alex

![export_scene_as_html_command_line](https://github.com/ansys/pyfluent-visualization/assets/31936244/2be28abe-4d46-46ac-b370-6f0b9bff1d5b)

**Comment by prmukherj** [comment]
The following code can be used:

>>> from ansys.fluent.visualization.pyvista import pyvista_windows_manager
>>> set_config(blocking=True, set_view_on_display="isometric")
>>> pyvista_windows_manager.open_window("w1")
>>> active_window = pyvista_windows_manager.get_window("w1")
>>> active_window.show_window = False 
>>> active_window.post_object = mesh1
>>> active_window.plot()
>>> plotter= pyvista_windows_manager.get_plotter("w1")
>>> plotter.export_html('manifold.html',  backend='panel')

Refer: https://github.com/ansys/pyfluent-visualization/pull/236

**Comment by amscosta** [comment]
Great. Many Thanks.

Em qui., 25 de jul. de 2024, 03:28, Prithwish Mukherjee <
***@***.***> escreveu:
