### ISSUE TITLE
ansys-fluent-visualization error in importing graphics

### ISSUE THREAD

**Issue by nehajoshi4598** [ansys/pyfluent-visualization#397]
### 📝 Description of the example

I am getting error in this code from ansys.fluent.visualization.pyvista import Graphics 
This is the error , 
![PyFluent Visualization](https://github.com/ansys/pyfluent-visualization/assets/83366135/b269e703-e765-4bcb-a42b-d22d617c2598)
AttributeError: module 'PySide6.QtPrintSupport' has no attribute 'QDragEnterEvent'

### 📁 Files needed for running the example

![PyFluent Visualization](https://github.com/ansys/pyfluent-visualization/assets/83366135/9e0b3ddd-d7d0-4899-9068-8fc34fc46573)

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

ANSYS 2024 R1

### 🐍 Which Python version are you using?

3.11

### 📦 Installed packages

```shell
pip install ansys-fluent-core
pip install ansys-fluent-parametric
pip install ansys-fluent-visualization
```

**Comment by prmukherj** [comment]
@nehajoshi4598, could you please re-run using the latest release of py-visualization. Thank you.

**Comment by prmukherj** [comment]
Please open a new issue if this error persist with the latest version as well.
Thank you.
