### ISSUE TITLE
Current release of PyFluent (0.21) is incompatible with released version of pyfluent-visualization

### ISSUE THREAD

**Issue by RobPasMue** [ansys/pyfluent-visualization#398]
Pinging @ansys/pyfluent-admins for visibility.

Current PyFluent release is not compatible with the released versions of this package.

**Comment by prmukherj** [comment]
Just pushed the tag @seanpearsonuk.

**Comment by RobPasMue** [comment]
Fixed here, thanks! Still remaining ``pyfluent-parametric``
