### ISSUE TITLE
Incompatibile dependencies with PyFluent

### ISSUE THREAD

**Issue by RobPasMue** [ansys/pyfluent-visualization#407]
https://github.com/ansys/pyfluent-visualization/blob/97cbe766fae9c02d281ee17e762c4e9c057275ea/pyproject.toml#L33

Please align with PyFluent requirement - otherwise 0.21.3 onwards will be incompatible - this requires a new release.

I suggest you define the same requirement ``>=2.32.3``

Pinging @ansys/pyfluent-admins

**Comment by RobPasMue** [comment]
@prmukherj let me know if you need anything from my side.

**Comment by mkundu1** [comment]
Hi @RobPasMue, This issue is now fixed with the latest 0.10.1 release.

**Comment by RobPasMue** [comment]
Solved it, thanks!
